# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: codedroplet
    ports:
      - 5432:5432
    volumes: 
      - ./../.data:/var/lib/postgresql/data